### ISSUE TITLE
Sanic deprecation warning with 'Sanic.app(name=None)'

### ISSUE THREAD

**Issue by LewisGaul** [ensoft/entrance#6]
```
entrance/__main__.py:25: DeprecationWarning: Sanic(name=None) is deprecated and None value support for 
`name` will be removed in the next release. Please use Sanic(name='your_application_name') instead.
  app = sanic.Sanic(log_config=None)

$pip freeze | grep sanic
sanic==19.12.2

$python -V
Python 3.8.0

**Comment by LewisGaul** [comment]
@simonchatts 
I'd be happy to open a PR with a fix for this - do you have a suggestion on what to use as the name? I could use something like "EnTrance sample app", but what I'm not clear about is whether this module is intended to be used by people using EnTrance.

It seems a little strange to me to make `__main__` part of the library API, I'm not sure if it's intended to be or whether it's intended more as an example to be copied? Maybe we should allow/enforce the app name to be configured in the `config.yml` file?

**Comment by simonchatts** [comment]
Thanks Lewis - a PR would be great.

From a quick look at the Sanic code, I don't think the name is important at all for us, and any string would be fine. Maybe `entrance-app`?

I don't see a reason to require configuration - I suspect it has literally zero impact unless someone is doing something pretty far-out like running multiple Sanic apps from the same process.

The `__main__` is there so that [in simple cases](https://github.com/ensoft/entrance/blob/master/samples/1_notes/svr/run) you can just run `python -m entrance` without writing any Python code at all. This is somewhat niche, so if there is a good reason to reconsider this, I'm open to that.

**Comment by LewisGaul** [comment]
> From a quick look at the Sanic code, I don't think the name is important at all for us, and any string would be fine. Maybe `entrance-app`?

Sure, I'll go with that.

> The `__main__` is there so that [in simple cases](https://github.com/ensoft/entrance/blob/master/samples/1_notes/svr/run) you can just run `python -m entrance` without writing any Python code at all. This is somewhat niche, so if there is a good reason to reconsider this, I'm open to that.

Right, got it. Sorry, this is a little off-topic, but what I'm confused by is [example 2](https://github.com/ensoft/entrance/blob/master/samples/2_shell/svr/run.py#L55) where `from entrance.__main__ import main` is used, which seems to suggest this is recommended usage? This seems pretty handy, but I'm put off by the import from `__main__` and would prefer it to be made available in a regular module (or at package level in `__init__.py`). I'm currently opting for `runpy.run_module("entrance", run_name="__main__")` instead.

Anyway, to bring relevance back to this issue, I was just thinking that if the `main()` function is intended as part of the API, maybe it should allow customising the app name (e.g. via the config file), but as you point out that shouldn't really be needed!

**Comment by simonchatts** [comment]
Yes, it's a good point. The example 2 thing is just trying to provide some custom Python, and then launch into the standard `main`, all from a single module.

We can certainly pull the `main` function out into a regular library module, and invoke that from the package `__main__.py`. Would that solve the confusion, or is there a better way?

**Comment by LewisGaul** [comment]
I was going to suggest an `entrance.App` wrapping `sanic.Sanic` which would provide the functionality in the `start()` function, but then realised you probably either want everything provided by `main()` or to do it all yourself.

The only objection I have really is the import from `__main__` :) Here's the options I'd suggest:
 1) Use `runpy.run_module("entrance", run_name="__main__")` instead of `from entrance.__main__ import main; main(*sys.argv[1:]))` in the examples (making this the recommended way to do it), since I find this a more explicit technique (it confused me for a moment that `__name__` in `__main__` when importing is actually `entrance.__main__`, meaning the existing technique does work as expected, but is perhaps non-obvious!)
 2) Provide a `main()` function in e.g. `__init__.py` that performs the runpy method, allowing `from entrance import main; main()` without having to move any code around.
 3) Move most of the contents of `__main__.py` into an `app.py` module which becomes a more normal public API, which can be used by `__main__.py`.

I think 3) is my least favourite, and I have a slight preference for 2) since using `runpy` might be foreign to some people(?). FWIW I have confirmed option 2 works - LMK if you'd like a PR.

**Comment by simonchatts** [comment]
Thanks for the analysis of the tradeoffs! Yes a PR for whichever you feel is most appropriate would be great.
